### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by charithjob** [openaphid/android-flip#109]
How to fix this error

at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:809)
at android.graphics.Bitmap.createBitmap(Bitmap.java:786)
at android.graphics.Bitmap.createBitmap(Bitmap.java:753)
at com.aphidmobile.flip.GrabIt.takeScreenshot(GrabIt.java:26)
at com.aphidmobile.flip.ViewDualCards.loadView(ViewDualCards.java:82)
at com.aphidmobile.flip.FlipCards.reloadTexture(FlipCards.java:128)
at com.aphidmobile.flip.FlipRenderer.updateTexture(FlipRenderer.java:143)
at com.aphidmobile.flip.FlipViewController.onLayout(FlipViewController.java:374)

**Comment by Ram8948** [comment]
i also have same problem. any solution

**Comment by rameshkec85** [comment]
Getting the same issue. Is there any solution for this ?
