### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by parkwh** [openaphid/android-flip#21]
Sometimes flip when a problem occurs.

Can solve it?

Thanks~

12-11 16:09:47.751: D/OpenAphid(14478): create bitmap 720x1142

 FATAL EXCEPTION: main
 java.lang.OutOfMemoryError
    at android.graphics.Bitmap.nativeCreate(Native Method)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:640)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:620)
    at com.aphidmobile.flip.GrabIt.takeScreenshot(GrabIt.java:33)
    at com.aphidmobile.flip.ViewDualCards.setView(ViewDualCards.java:75)
    at com.aphidmobile.flip.FlipCards.reloadTexture(FlipCards.java:106)
    at com.aphidmobile.flip.FlipRenderer.updateTexture(FlipRenderer.java:135)
    at com.aphidmobile.flip.FlipViewController.onLayout(FlipViewController.java:327)
    at android.view.View.layout(View.java:14063)
    at android.view.ViewGroup.layout(ViewGroup.java:4605)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
    at android.view.View.layout(View.java:14063)
    at android.view.ViewGroup.layout(ViewGroup.java:4605)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
    at android.view.View.layout(View.java:14063)
    at android.view.ViewGroup.layout(ViewGroup.java:4605)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
    at android.view.View.layout(View.java:14063)
    at android.view.ViewGroup.layout(ViewGroup.java:4605)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1998)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1819)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1116)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4533)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
    at android.view.Choreographer.doCallbacks(Choreographer.java:555)
    at android.view.Choreographer.doFrame(Choreographer.java:525)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
    at android.os.Handler.handleCallback(Handler.java:615)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4943)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1036)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:803)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by Ram8948** [comment]
I also have same issue. any solution please.

**Comment by rameshkec85** [comment]
I have the same issue even using latest library.
